export default {
  GET_IMAGES_CONFIG: 'GET_IMAGES_CONFIG',
  GET_IMAGES_CONFIG_START: 'GET_IMAGES_CONFIG_START',
  GET_IMAGES_CONFIG_SUCCESS: 'GET_IMAGES_CONFIG_SUCCESS',
  GET_IMAGES_CONFIG_FAILURE: 'GET_IMAGES_CONFIG_FAILURE',
  GET_ALL_GENRES: 'GET_ALL_GENRES',
  GET_ALL_GENRES_START: 'GET_ALL_GENRES_START',
  GET_ALL_GENRES_SUCCESS: 'GET_ALL_GENRES_SUCCESS',
  GET_ALL_GENRES_FAILURE: 'GET_ALL_GENRES_FAILURE',
};
