export default {
  GET_DISCOVER_MOVIES: 'GET_DISCOVER_MOVIES',
  GET_DISCOVER_MOVIES_START: 'GET_DISCOVER_MOVIES_START',
  GET_DISCOVER_MOVIES_SUCCESS: 'GET_DISCOVER_MOVIES_SUCCESS',
  GET_DISCOVER_MOVIES_FAILURE: 'GET_DISCOVER_MOVIES_FAILURE',
};
