export default {
  GET_DISCOVER_MOVIES: 'GET_DISCOVER_MOVIES',
  GET_DISCOVER_MOVIES_START: 'GET_DISCOVER_MOVIES_START',
  GET_DISCOVER_MOVIES_SUCCESS: 'GET_DISCOVER_MOVIES_SUCCESS',
  GET_DISCOVER_MOVIES_FAILURE: 'GET_DISCOVER_MOVIES_FAILURE',
  GET_MORE_DISCOVER_MOVIES: 'GET_MORE_DISCOVER_MOVIES',
  GET_MORE_DISCOVER_MOVIES_START: 'GET_MORE_DISCOVER_MOVIES_START',
  GET_MORE_DISCOVER_MOVIES_SUCCESS: 'GET_MORE_DISCOVER_MOVIES_SUCCESS',
  GET_MORE_DISCOVER_MOVIES_FAILURE: 'GET_MORE_DISCOVER_MOVIES_FAILURE',
  DISCOVER_MOVIES_SET_SORT_BY: 'DISCOVER_MOVIES_SET_SORT_BY',
  DISCOVER_MOVIES_TOGGLE_GENRE_FILTER: 'DISCOVER_MOVIES_TOGGLE_GENRE_FILTER',
  DISCOVER_MOVIES_SET_RELEASE_YEAR: 'DISCOVER_MOVIES_SET_RELEASE_YEAR',
};
